### PR TITLE
Quiz

### PR DESCRIPTION
**Pull request by madduxTim**

### CODE REVIEW

**Comment by zoeames** [comment]
Hey Tim,
An excellent start to the quiz!  looks really good!  A few minor changes:
1.  try to make use of the row class in bootstrap.  it will add some padding to make your cards look cleaner
2.  when i click on a card i see a background color change (yay!) but i don't see a thicker border.
3.  when i click on a card after clicking on another card it changes the color of the original card back to normal.  it should do that AND select the new card i clicked on (ie i should not have to click twice to get the 2nd card to change)

Once you get those few things fixed you will be good!

**Comment by zoeames** [comment]
OMG NICE QUIZ!!!!  awesome job you totally nailed this one!!!!!
You have a couple lines of commented code here and there.  go ahead and remove those and then update this PR.  Once you have updated the PR you can go ahead and merge
👍

**Comment by zoeames** [comment]
hey tim, Looks really good!  only one minor bug:  when i click on a car the border gets thick but the border-color changes to black for all of them.  once you fix that you will be ready to merge

**Comment by madduxTim** [comment]
Thanks Zoe! Maybe not the elegant solution, but it is (a) dynamic and above
all (b) functional... Happy to tear down and include the necessary
functionality some other way if necessary.

**Comment by zoeames** [comment]
works for me 👍

**Pull request merged**
